### ISSUE TITLE
Rating control does not return results

### ISSUE THREAD

**Issue by mh246** [andrewtelnov/surveyjs#3]
Rating control selections are not added to the survey result.  This occurs using the default values (1 to 5), and when setting custom values.  

If you make a Rating control 'Required' surveyjs will always identify it as unselected ("Please answer the question" alert appears).

Example survey:
var survey = new Survey.Survey(
{pages:[{name:"page1",questions:[{type:"rating",isRequired:true,name:"question1"}]}]});

**Comment by andrewtelnov** [comment]
Hi,
I just tried with the latest source and it works fine. I have tried bootstrap and nobootstrap versions. I did not try npm version. I am going to update it shortly. 
Here is my html:
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Product Feedback</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.0/knockout-min.js"></script>
    <script src="http://surveyjs.org/js/survey.bootstrap.min.js"></script>
    <link rel="stylesheet" href="http://surveyjs.org/css/survey.css" />
</head>
<body>
    <div id="dxsurvey"></div>
    <div id="dxsurveyJson"></div>
    <script>
        var json =  {pages:[{name:"page1",questions:[{type:"rating",isRequired:true,name:"question1"}]}]};
        var survey = new Survey.Survey(json, "dxsurvey");
        survey.onComplete.add(function (s) { document.getElementById("dxsurvey").innerHTML = "Done!"; document.getElementById("dxsurveyJson").innerHTML = "The results are: \n" + JSON.stringify(survey.data); });
    </script>
</body>
</html>

**Comment by andrewtelnov** [comment]
Hi,
I just tried with the latest source and it works fine. I have tried bootstrap and nobootstrap versions. I did not try npm version. I am going to update it shortly. 
Could you please try with this links?
`
    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.0/knockout-min.js"></script>
    <script src="http://surveyjs.org/js/survey.min.js"></script>
    <link rel="stylesheet" href="http://surveyjs.org/css/survey.css" />
`
Thank you,
Andrew

**Comment by andrewtelnov** [comment]
I have published a new version into npm. I hope the issue is resolved.

**Comment by mh246** [comment]
Hi Andrew.  I'm still experiencing the same issue (using the most recent cut).  I've done a bit more digging and found that it only occurs with the bootstrap version.  I can replicate it using Windows desktop Chrome, Internet Explorer, and mobile Chrome on Android.

Importantly, I can see the issue when I use the Visual Designer and run the survey from there (so I've eliminated my setup from the equation).

I'm traveling right now so I don't have a ton of time to debug, but I'll try to take a closer look when I have a chance..

-mat

**Comment by andrewtelnov** [comment]
Yes, I have managed to reproduced this issue. I guess it is related to the Visual Editor. 
I will work on the fix. I will keep you inform.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
ok, Here is the reason of the issue: http://stackoverflow.com/questions/20077475/knockout-bootstrap-3-radio-buttons
I will try to find the workaround.

**Comment by andrewtelnov** [comment]
Fixed-
Andrew-
